version: '2'

 

services:
    web:
        build:
            context: ./LogService
            dockerfile: Dockerfile
        ports:
            - "8001-8003:6000"
    balanceador:
        build:
            context: ./BalanceadorRoundRobin
            dockerfile: Dockerfile
        ports:
            - "9000:6000"
        
    db:
        image: mongo:3.6.1
        container_name: db
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
        
volumes:
    mongodb:
    mongodb_config: